### ISSUE TITLE
切换月份后，选择的日期会消失

### ISSUE THREAD

**Issue by ccccps** [zhaokuohaha/vue-multi-date-picker#1]
<img width="278" alt="2017-11-24 13 04 45" src="https://user-images.githubusercontent.com/25984670/33195104-23f82e42-d118-11e7-9320-1515aa597e6e.png">
<img width="271" alt="2017-11-24 13 04 53" src="https://user-images.githubusercontent.com/25984670/33195105-244cc11e-d118-11e7-8a0c-1437b3ad7a58.png">
<img width="275" alt="2017-11-24 13 05 00" src="https://user-images.githubusercontent.com/25984670/33195106-24a25296-d118-11e7-8111-0233e9e59a52.png">
如图片所示，在11月选完日期后，切换到12月，再切换回11月，选择的日期会消失。

虽然按下确定后有正确选择，但在按下确定前会不知道自己择了什么。

**Comment by zhaokuohaha** [comment]
已经修复， 是因为日期比较方法不正确导致的， 更新依赖后即可
