### ISSUE TITLE
日期错误

### ISSUE THREAD

**Issue by xiayy0328** [zhaokuohaha/vue-multi-date-picker#2]
选完日期之后，我将日期存储在本地，再次进入页面取出日期 进行赋值
 item.toLocaleDateString is not a function"

found in

---> <MDatePicker> at node_modules/_vue-multi-date-picker@1.2.0@vue-multi-date-picker/src/lib/multiDatePicker.vue

**Comment by zhaokuohaha** [comment]
log 一下从本地存储取出的日期的值看看是不是没有正确取到?

**Comment by xiayy0328** [comment]
我log看了一下，本地存储的东西——————Mon Nov 06 2017 00:00:00 GMT+0800 (CST),Tue Nov 07 2017 00:00:00 GMT+0800 (CST),Wed Nov 08 2017 00:00:00 GMT+0800 (CST),Thu Nov 09 2017 00:00:00 GMT+0800 (CST)———————— 是没问题的。<m-date-picker  v-model="date" :multi="multi"></m-date-picker> 取出后我赋值给date 然后就报上面那个错误了

**Comment by zhaokuohaha** [comment]
你是存到localStorage了把, localStorage存储的数据类型是字符串,key和value都是,
 所以你拿出来的数据应该是字符串类型, 
导致直接调用日期类型的方法会报错

![qq 20171127145323](https://user-images.githubusercontent.com/16274628/33254418-9cc2d698-d383-11e7-838d-8ef7d8e6bc79.png)

取出来之后把字符串先转成对应的日期应该就可以了
![qq 20171127150154](https://user-images.githubusercontent.com/16274628/33254504-eebb086c-d383-11e7-91b3-848a215e1638.png)
