### ISSUE TITLE
月份与语言问题

### ISSUE THREAD

**Issue by ccccps** [zhaokuohaha/vue-multi-date-picker#3]
①
在12月的时候切换下个月会变13月
在1月的时候切换上个月会变0月
可以改为变成下一年或上一年吗
②
语言能依照系统语言调整或自己设定吗

谢谢！

**Comment by zhaokuohaha** [comment]
这两天着手解决 😆

**Comment by zhaokuohaha** [comment]
新版本已解决 [1.2.2](https://github.com/zhaokuohaha/vue-multi-date-picker/releases/tag/1.2.2)

**Comment by ccccps** [comment]
月份没问题了！谢谢！
但「周六」的显示不见了。
另外，display如下设定似乎没效果。
```
<m-date-picker 
  v-model="d.dates" 
  :display="['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Y', 'M', 'Cancel', 'OK']"
  :multi="true" />
```

**Comment by zhaokuohaha** [comment]
😭 上周更新的比较匆忙， 这个估计又得等周末才能修了 😆

**Comment by zhaokuohaha** [comment]
自定义语言的`prop`重命名为`:disp`
